databases:
  - name: codeleapdb
    plan: free
    databaseName: codeleap
    user: codeleap

services:
  - type: web
    plan: free
    name: codeleap
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: codeleapdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4